//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public Deal()
        {
            this.GoodsInDeal = new HashSet<GoodsInDeal>();
            this.Reminder = new HashSet<Reminder>();
            this.TaskBD = new HashSet<TaskBD>();
        }
    
        public int ID { get; set; }
        public int ID_Condition { get; set; }
        public int ID_People { get; set; }
        public int ID_Staff { get; set; }
        public decimal Price { get; set; }
        public decimal Paid { get; set; }
        public System.DateTime DateDeal { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
    
        public virtual ConditionDeal ConditionDeal { get; set; }
        public virtual People People { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<GoodsInDeal> GoodsInDeal { get; set; }
        public virtual ICollection<Reminder> Reminder { get; set; }
        public virtual ICollection<TaskBD> TaskBD { get; set; }
    }
}
