//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.GoodsInDeal = new HashSet<GoodsInDeal>();
            this.Reminder = new HashSet<Reminder>();
            this.TaskBD = new HashSet<TaskBD>();
        }
    
        public int ID { get; set; }
        public int ID_TypeGoods { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int CountUnits { get; set; }
    
        public virtual TypeGoods TypeGoods { get; set; }
        public virtual ICollection<GoodsInDeal> GoodsInDeal { get; set; }
        public virtual ICollection<Reminder> Reminder { get; set; }
        public virtual ICollection<TaskBD> TaskBD { get; set; }
    }
}
