//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInDeal
    {
        public int ID { get; set; }
        public int ID_Deal { get; set; }
        public int ID_Goods { get; set; }
        public int CountUnits { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
