//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public People()
        {
            this.Deal = new HashSet<Deal>();
            this.EmailPeople = new HashSet<EmailPeople>();
            this.PhonePeople = new HashSet<PhonePeople>();
            this.Reminder = new HashSet<Reminder>();
            this.TaskBD = new HashSet<TaskBD>();
        }
    
        public int ID { get; set; }
        public int ID_CardClient { get; set; }
        public Nullable<int> ID_Post { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual CardClient CardClient { get; set; }
        public virtual ICollection<Deal> Deal { get; set; }
        public virtual ICollection<EmailPeople> EmailPeople { get; set; }
        public virtual PostPeople PostPeople { get; set; }
        public virtual ICollection<PhonePeople> PhonePeople { get; set; }
        public virtual ICollection<Reminder> Reminder { get; set; }
        public virtual ICollection<TaskBD> TaskBD { get; set; }
    }
}
