//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ID { get; set; }
        public int ID_Post { get; set; }
        public Nullable<int> ID_Staff { get; set; }
        public int ID_StaffSender { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> ID_People { get; set; }
        public Nullable<int> ID_Deal { get; set; }
        public Nullable<int> ID_Goods { get; set; }
        public System.DateTime DateEvent { get; set; }
        public string Description { get; set; }
    
        public virtual CardClient CardClient { get; set; }
        public virtual Deal Deal { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual People People { get; set; }
        public virtual PostPeople PostPeople { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
