//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Deal = new HashSet<Deal>();
            this.EmailStaff = new HashSet<EmailStaff>();
            this.PhoneStaff = new HashSet<PhoneStaff>();
            this.Reminder = new HashSet<Reminder>();
            this.Reminder1 = new HashSet<Reminder>();
            this.TaskBD = new HashSet<TaskBD>();
            this.TaskBD1 = new HashSet<TaskBD>();
        }
    
        public int ID { get; set; }
        public int ID_Post { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> ID_City { get; set; }
        public string Address { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Deal> Deal { get; set; }
        public virtual ICollection<EmailStaff> EmailStaff { get; set; }
        public virtual ICollection<PhoneStaff> PhoneStaff { get; set; }
        public virtual PostPeople PostPeople { get; set; }
        public virtual ICollection<Reminder> Reminder { get; set; }
        public virtual ICollection<Reminder> Reminder1 { get; set; }
        public virtual ICollection<TaskBD> TaskBD { get; set; }
        public virtual ICollection<TaskBD> TaskBD1 { get; set; }
    }
}
