//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Client.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePhone
    {
        public TypePhone()
        {
            this.PhonePeople = new HashSet<PhonePeople>();
            this.PhoneStaff = new HashSet<PhoneStaff>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PhonePeople> PhonePeople { get; set; }
        public virtual ICollection<PhoneStaff> PhoneStaff { get; set; }
    }
}
